---
# Source: postgres-db-chart/templates/pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: postgres-db-chart
  name: pv-pg-postgres-db-chart
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Ti
  hostPath:
    path: /path/to/data
  persistentVolumeReclaimPolicy: Retain
---
# Source: postgres-db-chart/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-db-chart
  name: pvc-pg-postgres-db-chart
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Ti
---
# Source: postgres-db-chart/templates/serv.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-db-chart
  name: service-pg-postgres-db-chart
spec:
  ports:
  - nodePort: 30432
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-db-chart
  type: NodePort
---
# Source: postgres-db-chart/templates/depl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-db-chart
    chart: postgres-db-chart-0.1.0
    release: pg
  name: pg-postgres-db-chart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db-chart
  template:
    metadata:
      labels:
        app: postgres-db-chart
    spec:
      containers:
      - image: pgvector/pgvector:pg16
        imagePullPolicy: IfNotPresent
        name: postgres-db-chart
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: aithenadb-secret
        resources:
          limits:
            cpu: "110"
            memory: 1400Gi
          requests:
            cpu: "1"
            memory: 1300Gi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: storage-pg-postgres-db-chart
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: storage-pg-postgres-db-chart
        persistentVolumeClaim:
          claimName: pvc-pg-postgres-db-chart
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 1400Gi
