replicaCount: 1

image:
  repository: pgvector/pgvector
  pullPolicy: IfNotPresent
  tag: "pg16"
  
service:
  type: NodePort
  port: 5432
  targetPort: 5432
  nodePort: 30432 

container:
  mountPath: "/var/lib/postgresql/data"

persistentVolume:
  storage: 10Ti
  hostPath: /polus2/schaubnj/.data/pgvector

persistentVolumeClaim:
  storage: 10Ti

nodeSelector: {}

tolerations: []

affinity: {}
