apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama-ss-set
spec:
  serviceName: ollama-ss-headless
  replicas: 2
  selector:
    matchLabels:
      app: ollama-ss
  template:
    metadata:
      labels:
        app: ollama-ss
    spec:
      containers:
      - name: ollama-ss
        image: ollama/ollama:0.4.2
        env:
        # Field reference to the pod name
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ["/bin/sh", "-c", "export CUDA_VISIBLE_DEVICES=$(echo $POD_NAME | awk -F'-' '{print $NF}') && /usr/bin/ollama serve"]
        volumeMounts:
          - name: pvc-ollama-ss
            mountPath: "/root/.ollama"
  volumeClaimTemplates:
  - metadata:
      name: pvc-ollama-ss
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-ss-headless
spec:
  clusterIP: None
  selector:
    app: ollama-ss
  ports:
  - port: 11434
    name: ollama-ss