apiVersion: v1
kind: PersistentVolume
metadata:
  name: litellm-db-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/data/litellm-db"
    type: DirectoryOrCreate 