apiVersion: v1
kind: PersistentVolume
metadata:
  name: litellm-db-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/polus2/velezramirezc2/.data/litellm_db_data"
    type: DirectoryOrCreate 