apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "arctic-chart.fullname" . }}
  labels:
    {{- include "arctic-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "arctic-chart.fullname" . }}-headless
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  selector:
    matchLabels:
      {{- include "arctic-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arctic-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - python
        - -m
        - arctic_inference.embedding.replica_manager
        args:
        - "--model"
        - "{{ .Values.args.model }}"
        - "--trust-remote-code"
        - "--host"
        - "{{ .Values.args.host }}"
        - "--port"
        - "{{ .Values.args.port }}"
        - "--num-replicas"
        - "{{ .Values.args.numReplicas }}"
        - "--task"
        - "{{ .Values.args.task }}"
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        resources:
          requests:
            nvidia.com/gpu: {{ .Values.resources.requests.gpu }}
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            nvidia.com/gpu: {{ .Values.resources.limits.gpu }}
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: cache-volume
          mountPath: /root/.cache/huggingface
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.shm.sizeLimit }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: cache-volume
    spec:
      accessModes:
        {{- toYaml .Values.persistence.accessModes | nindent 8 }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      {{- if .Values.persistence.pv.create }}
      volumeName: {{ .Values.persistence.pv.name }}
      {{- end }}
  {{- end }}
