  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

qdrant-chart:
  replicaCount: 1

  image:
    repository: qdrant/qdrant
    pullPolicy: IfNotPresent
    tag: "v1.11.3"
    
  service:
    type: NodePort
    port: 6333
    targetPort: 6333
    nodePort: 30333 

  container:
    mountPath: "/qdrant/storage"
  # resources:
    # requests:
    #   memory: "64Mi"
    #   cpu: "250m"
    # limits:
    #   memory: "128Mi"
    #   cpu: "500m"

  persistentVolume:
    storage: 50Gi
    hostPath: /path/to/db-data

  persistentVolumeClaim:
    storage: 50Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}


ollama-chart:
  replicaCount: 1

  image:
    repository: ollama/ollama
    pullPolicy: IfNotPresent
    tag: "0.3.10"

  service:
    type: NodePort
    port: 11434
    targetPort: 11434
    nodePort: 32434 

  container:
    mountPath: "/root/.ollama"

  persistentVolume:
    storage: 50Gi
    hostPath: /path/to/ollama-data

  persistentVolumeClaim:
    storage: 50Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}


aithena-services-chart:
  replicaCount: 1

  image:
    repository: agerardin/aithena-services
    pullPolicy: IfNotPresent
    tag: "0.1.0-dev3"

  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 32080 

  container:
    mountPath: "/mnt/config"
    # resources:
    #   requests:
    #     memory: "500Mi"
    #     cpu: "1"
    #   limits:
    #     memory: "2Gi"
    #     cpu: "1"

  secrets:
    - name: aithena-services-secret

  env:
    - name: OLLAMA_HOST
      value: "http://service-ollama.test-aithena.svc.cluster.local:11434"

  persistentVolume:
    storage: 5Mi
    hostPath: /path/to/aithena-services-data

  persistentVolumeClaim:
    storage: 5Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}


ask-aithena-agent-chart:
  replicaCount: 1

  image:
    repository: agerardin/ask-aithena-agent
    pullPolicy: IfNotPresent
    tag: "0.1.2-dev1"

  service:
    type: NodePort
    port: 8000
    targetPort: 8000
    nodePort: 32008 

  env:
    - name: AITHENA_SERVICES_URL
      value: "http://service-ais.test-aithena.svc.cluster.local:80"
    - name: EMBED_MODEL
      value: "nomic-embed-text"
    - name: CHAT_MODEL
      value: "llama3.1:latest"
    - name: DB_HOST
      value: "service-qdrant.test-aithena.svc.cluster.local"
    - name: DB_PORT
      value: "6333"
    - name: DOC_COLLECTION
      value: "full_arxiv_abstracts_nomic768"

  nodeSelector: {}

  tolerations: []

  affinity: {}

  persistentVolume:
    storage: 5Mi
    hostPath: /path/to/ask-aithena-agent-data

  persistentVolumeClaim:
    storage: 5Mi



ask-aithena-app-chart:
  replicaCount: 1

  image:
    repository: agerardin/ask-aithena-app
    pullPolicy: IfNotPresent
    tag: "0.1.0-dev3"

  service:
    type: NodePort
    port: 8765
    targetPort: 8765
    nodePort: 32065 

  env:
    - name: ASK_AITHENA_API_URL
      value: "http://service-ask-aithena-agent.test-aithena.svc.cluster.local:8000"
    - name: ASK_AITHENA_STREAM
      value: True

  nodeSelector: {}

  tolerations: []

  affinity: {}

  persistentVolume:
    storage: 5Mi
    hostPath: /path/to/ask-aithena-app-data

  persistentVolumeClaim:
    storage: 5Mi
