apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service-management
spec:
  selector:
    app: rabbitmq
  ports:
  - name: management
    port: 15672
    targetPort: 15672
    nodePort: 32104
  type: NodePort
