apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-load-balancer-microk8s-conf
  namespace: ingress
data:
  # Timeouts from your ingress annotations, using correct integer format
  proxy-connect-timeout: "14400"
  proxy-read-timeout: "14400"
  proxy-send-timeout: "14400"
  client-header-timeout: "14400"
  client-body-timeout: "14400"
  
  # Keepalive settings using direct keys instead of snippets
  keepalive-timeout: "14400"
  keepalive-requests: "10000"

  # Fix for the parsing error
  proxy-next-upstream-timeout: "600"

  # Other settings from your original file and annotations
  proxy-body-size: "100m"
  proxy-buffering: "off"
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
