apiVersion: v1
kind: Service
metadata:
  name: redis-service-external
  namespace: box
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 32379
      protocol: TCP
  selector:
    app: redis