apiVersion: apps/v1
kind: Deployment
metadata:
  name: ask-aithena-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ask-aithena-agent
  template:
    metadata:
      labels:
        app: ask-aithena-agent
    spec:
      containers:
      - name: ask-aithena-agent
        image: camilovelezr/aithena-ask-aithena-agent:0.1.2-dev0
        ports:
        - containerPort: 8000
        env:
          - name: AITHENA_SERVICES_URL
            value: "http://aithena-services-service-010.default.svc.cluster.local:80"
          - name: EMBED_MODEL
            value: "nomic-embed-text"
          - name: CHAT_MODEL
            value: "llama3.1"
          - name: DB_HOST
            value: "qdrant-service.default.svc.cluster.local"
          - name: DB_PORT
            value: "6333"
        resources:
          requests:
            memory: "500Mi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "1"
