apiVersion: v1
kind: Service
metadata:
  name: ask-aithena-agent-service
spec:
  type: NodePort
  selector:
    app: ask-aithena-agent
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30503  # Specify a port in the range 30000-32767
