{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ollama-chart.pvName" . }}
  labels:
    {{- include "ollama-chart.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.storage.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.storage.reclaimPolicy }}
  storageClassName: {{ .Values.storage.storageClassName }}
  hostPath:
    path: {{ .Values.storage.hostPath.path | quote }}
    type: {{ .Values.storage.hostPath.type }}
{{- end }}
