apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama-chart.fullname" . }}-service
  labels:
    {{- include "ollama-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "ollama-chart.selectorLabels" . | nindent 4 }}
