# Default values for qdrantChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: agerardin/ask-aithena-app
  pullPolicy: IfNotPresent
  tag: "0.1.0-dev3"

service:
  type: NodePort
  port: 8765
  targetPort: 8765
  nodePort: 32065 

env:
  - name: ASK_AITHENA_API_URL
    value: "http://service-ask-aithena-agent.test-aithena.svc.cluster.local:8000"
  - name: ASK_AITHENA_STREAM
    value: True

nodeSelector: {}

tolerations: []

affinity: {}

persistentVolume:
  storage: 5Mi
  hostPath: /path/to/ask-aithena-app-data

persistentVolumeClaim:
  storage: 5Mi
