apiVersion: v1
kind: PersistentVolume
metadata:
  name: litellm-config-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/data/litellm-config"
    type: DirectoryOrCreate 