apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
type: Opaque
data:
  AZURE_API_KEY: QU01S1hid0lSUEhjYjRZWVRvNENucU81T3dVcElKUW1CbGFqbGpia09OQWdBSG81UmQ3ckpRUUo5OUFMQUNIWUh2NlhKM3czQUFBQkFDT0dDWkN2
  AZURE_API_BASE: aHR0cHM6Ly9uY2F0c3BvbHVzYWl0aGVuYS5vcGVuYWkuYXp1cmUuY29tLw==