apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
type: Opaque
data:
  # These are sample values - replace with real base64-encoded values in your environment
  AZURE_API_KEY: YmFzZTY0X2VuY29kZWRfc2VjcmV0X2tleQ==
  AZURE_API_BASE: YmFzZTY0X2VuY29kZWRfdXJs