apiVersion: v1
kind: Service
metadata:
  name: litellm-service
spec:
  selector:
    app: litellm
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 32102
    protocol: TCP
    name: http
  type: NodePort 