apiVersion: apps/v1
kind: Deployment
metadata:
  name: ask-aithena-app
  namespace: box
  labels:
    app: ask-aithena-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ask-aithena-app
  template:
    metadata:
      labels:
        app: ask-aithena-app
    spec:
      containers:
      - name: ask-aithena-app
        image: camilovelezr/ask-aithena-app:1.1.4
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ask-aithena-app-config
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.3"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always 