apiVersion: v1
kind: Service
metadata:
  name: {{ include "aithena-services-chart.fullname" . }}-service
  labels:
    {{- include "aithena-services-chart.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    {{- include "aithena-services-chart.selectorLabels" . | nindent 4 }}
