
replicaCount: 1

# schedule: "30 10 * * *"
schedule: "*/1 * * * *"
ttlSecondsAfterFinished: 86400 # keep failing pod 1 day for debugging
backoffLimit: 4

image:
  repository: agerardin/embed-arxiv
  tag: "0.1.0-dev0"
  pullPolicy: IfNotPresent

container:
  mountPath: "/inpDir"

  command:
    - python3
    - -m
    - polus.aithena.document_services.arxiv_abstract_ingestion
    - --date
    - "2024-10-16"

env:
  - name: DATA_DIR
    value: "/inpDir"
  - name: DOWNLOADS_DIR
    value: "downloads"
  - name: ARXIV_LIST_RECORDS_DIR
    value: "export.arxiv.org/ListRecords"
  - name: EMBED_URL
    value: "http://service-full-ask-aithena-ollama-chart.full-ai.svc.cluster.local:11434/api/embed"
  - name: DB_HOST
    value: "service-full-ask-aithena-qdrant-chart.full-ai.svc.cluster.local"
  - name: DB_PORT
    value: "6333"
  - name: DB_ABSTRACT_COLLECTION
    value: "full_arxiv_abstracts_nomic768"
  - name: BATCH_SIZE
    value: "1000"
  - name: EMBED_MODEL_BATCH_SIZE
    value: "10"
  - name: MAX_WORKERS
    value: "32"

resources:
  requests:
    memory: "512Mi"
    cpu: "1"


use_existing_volume: false

persistentVolume:
  storage: 5Gi
  hostPath: /polus2/gerardinad/projects/aithena/.data/arxiv-download/

persistentVolumeClaim:
  storage: 5Gi