apiVersion: apps/v1
kind: Deployment
metadata:
  name: ask-aithena-agent
  namespace: box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ask-aithena-agent
  template:
    metadata:
      labels:
        app: ask-aithena-agent
    spec:
      containers:
      - name: ask-aithena-agent
        image: camilovelezr/ask-aithena-agent:1.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: ask-aithena-agent-pv
          mountPath: /opt/prompts
        env:
        - name: LITELLM_URL
          value: http://litellm-service:4000/v1
        - name: LITELLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: ask-aithena-agent-secret
              key: litellm_api_key
        - name: USE_LOGFIRE
          value: "false"
        - name: RESPONDER_MODEL
          value: "gpt-4.1"
        - name: RESPONDER_MODEL_TEMPERATURE
          value: "0.4"
        - name: TALKER_MODEL
          value: "gpt-4.1"
        - name: TALKER_MODEL_TEMPERATURE
          value: "0.85"
        - name: SEMANTICS_MODEL
          value: "gpt-4.1"
        - name: SEMANTICS_TEMPERATURE
          value: "0.4"
        - name: AEGIS_ORCHESTRATOR_MODEL
          value: "o3"
        - name: AEGIS_ORCHESTRATOR_TEMPERATURE
          value: "1"
        - name: AEGIS_REFEREE_MODEL
          value: "o3"
        - name: AEGIS_REFEREE_TEMPERATURE
          value: "1"
        - name: SHIELD_MODEL
          value: "o4-mini"
        - name: SHIELD_TEMPERATURE
          value: "1"
        - name: EMBEDDING_TABLE
          value: "openalex.abstract_embeddings_arctic"
        - name: PROMPTS_DIR
          value: "/opt/prompts"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672/"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: SESSION_EXPIRATION_SECONDS
          value: "3600"
        - name: ARCTIC_HOST
          value: "arctic-direct-0-svc"
        - name: ARCTIC_PORT
          value: "8000"
        - name: HTTPX_TIMEOUT
          value: "60"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: ask-aithena-agent-pv
        persistentVolumeClaim:
          claimName: ask-aithena-agent-pvc