apiVersion: v1
kind: PersistentVolume
metadata:
  name: ask-aithena-agent-pv
spec:
  capacity:
    storage: 0.5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/polus2/velezramirezc2/.data/prompts"
    type: DirectoryOrCreate 