apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ask-aithena-agent-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: standard 