apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.headless.name }}
  labels:
    {{- include "postgres-chart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgres-chart.selectorLabels" . | nindent 4 }}
