apiVersion: v1
kind: Pod
metadata:
  name: db-cleanup-pod
  namespace: box
spec:
  containers:
  - name: cleanup-container
    image: busybox:1.35
    command: ["/bin/sh", "-c", "echo 'Wiping data directory with find...' && find /data -mindepth 1 -delete && echo 'Cleanup complete.'"]
    volumeMounts:
    - name: postgres-storage
      mountPath: /data
  volumes:
  - name: postgres-storage
    hostPath:
      path: /polus2/velezramirezc2/askaithena_data/jul25
  restartPolicy: Never 