apiVersion: v1
kind: Service
metadata:
  name: askaithena-db-headless
  namespace: box
  labels:
    app: askaithena-db
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: askaithena-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  # This creates DNS records:
  # askaithena-db-0.askaithena-db.box.svc.cluster.local
