apiVersion: v1
kind: Pod
metadata:
  name: postgres-deep-clean
  namespace: box
spec:
  containers:
  - name: cleanup
    image: busybox:1.35
    command: 
    - /bin/sh
    - -c
    - |
      echo "Starting deep cleanup..."
      echo "Current contents:"
      ls -la /data/
      echo ""
      echo "Checking for PostgreSQL data files:"
      if [ -d /data/base ]; then echo "Found base directory"; fi
      if [ -d /data/global ]; then echo "Found global directory"; fi
      if [ -f /data/PG_VERSION ]; then echo "Found PG_VERSION file"; fi
      echo ""
      echo "Removing all files and directories..."
      # Remove all visible files and directories
      rm -rf /data/*
      # Remove hidden files (like .s.PGSQL.* lock files)
      rm -rf /data/.[!.]*
      # Remove . and .. safe pattern
      rm -rf /data/..?*
      echo ""
      echo "Creating clean PGDATA directory with proper permissions..."
      # Ensure directory exists and has correct permissions
      chmod 700 /data
      chown -R 999:999 /data
      echo ""
      echo "Final state:"
      ls -la /data/
      echo "Cleanup complete!"
    volumeMounts:
    - name: postgres-storage
      mountPath: /data
    securityContext:
      runAsUser: 0  # Need root to change ownership
  volumes:
  - name: postgres-storage
    hostPath:
      path: /polus2/velezramirezc2/askaithena_data/jul25
  restartPolicy: Never
