apiVersion: v1
kind: Pod
metadata:
  name: postgres-debug
  namespace: box
spec:
  containers:
  - name: debug
    image: busybox:1.35
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: postgres-storage
      mountPath: /data
    securityContext:
      runAsUser: 0  # Run as root to see all files
  volumes:
  - name: postgres-storage
    hostPath:
      path: /polus2/velezramirezc2/askaithena_data/jul25
  restartPolicy: Never
