apiVersion: v1
kind: PersistentVolume
metadata:
  name: askaithena-db-pv
spec:
  storageClassName: truly-manual
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/polus2/velezramirezc2/askaithena_data/jul25"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - polus2
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
