apiVersion: v1
kind: Service
metadata:
  name: askaithena-db
  namespace: box
spec:
  selector:
    app: askaithena-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    nodePort: 30432
    name: postgres
  type: NodePort 