apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ask-aithena-agent-chart.fullname" . }}
  namespace: {{ include "ask-aithena-agent-chart.namespace" . }}
  labels:
    {{- include "ask-aithena-agent-chart.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ask-aithena-agent-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ask-aithena-agent-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "ask-aithena-agent-chart.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: prompts-volume
          mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
        {{- with .Values.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        - name: LITELLM_URL
          value: {{ .Values.env.litellm.url | default (printf "http://%s:4000/v1" (include "ask-aithena-chart.serviceName" (dict "Chart" (dict "Name" "litellm-chart") "Release" .Release))) | quote }}
        - name: LITELLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "ask-aithena-agent-chart.secretName" . }}
              key: {{ .Values.secret.litellmApiKeyName }}
        - name: USE_LOGFIRE
          value: {{ .Values.env.logfire.useLogfire | quote }}
        - name: RESPONDER_MODEL
          value: {{ .Values.env.models.responder.model | quote }}
        - name: RESPONDER_MODEL_TEMPERATURE
          value: {{ .Values.env.models.responder.temperature | quote }}
        - name: TALKER_MODEL
          value: {{ .Values.env.models.talker.model | quote }}
        - name: TALKER_MODEL_TEMPERATURE
          value: {{ .Values.env.models.talker.temperature | quote }}
        - name: SEMANTICS_MODEL
          value: {{ .Values.env.models.semantics.model | quote }}
        - name: SEMANTICS_TEMPERATURE
          value: {{ .Values.env.models.semantics.temperature | quote }}
        - name: AEGIS_ORCHESTRATOR_MODEL
          value: {{ .Values.env.models.aegisOrchestrator.model | quote }}
        - name: AEGIS_ORCHESTRATOR_TEMPERATURE
          value: {{ .Values.env.models.aegisOrchestrator.temperature | quote }}
        - name: AEGIS_REFEREE_MODEL
          value: {{ .Values.env.models.aegisReferee.model | quote }}
        - name: AEGIS_REFEREE_TEMPERATURE
          value: {{ .Values.env.models.aegisReferee.temperature | quote }}
        - name: SHIELD_MODEL
          value: {{ .Values.env.models.shield.model | quote }}
        - name: SHIELD_TEMPERATURE
          value: {{ .Values.env.models.shield.temperature | quote }}
        - name: EMBEDDING_TABLE
          value: {{ .Values.env.database.embeddingTable | quote }}
        - name: PROMPTS_DIR
          value: {{ .Values.env.prompts.directory | quote }}
        - name: RABBITMQ_URL
          value: "amqp://{{ .Values.rabbitmq.defaultUser }}:{{ .Values.rabbitmq.defaultPass }}@{{ include "ask-aithena-chart.serviceName" (dict "Chart" (dict "Name" "rabbitmq-chart") "Release" .Release) }}-internal:5672/"
        - name: ARCTIC_HOST
          value: {{ include "ask-aithena-chart.serviceName" (dict "Chart" (dict "Name" "arctic-chart") "Release" .Release) }}
        - name: ARCTIC_PORT
          value: {{ .Values.env.arctic.port | quote }}
        - name: HTTPX_TIMEOUT
          value: {{ .Values.env.http.timeout | quote }}
        {{- with .Values.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.probes.readiness.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readiness.httpGet.path }}
            port: {{ .Values.probes.readiness.httpGet.port }}
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          successThreshold: {{ .Values.probes.readiness.successThreshold }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
        {{- end }}
        {{- if .Values.probes.liveness.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.liveness.httpGet.path }}
            port: {{ .Values.probes.liveness.httpGet.port }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          successThreshold: {{ .Values.probes.liveness.successThreshold }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: prompts-volume
        persistentVolumeClaim:
          claimName: {{ include "ask-aithena-agent-chart.pvcName" . }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
