apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arctic-direct-pvc
  namespace: box
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: manual
  volumeMode: Filesystem