apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /polus2/velezramirezc2/.data/nginx_config
    type: DirectoryOrCreate
  volumeMode: Filesystem 