
replicaCount: 1

schedule: "*/1 * * * *"
ttlSecondsAfterFinished: 86400 # keep failing pod 1 day for debugging
backoffLimit: 4

image:
  repository: agerardin/oaipmh-client
  pullPolicy: IfNotPresent
  tag: "0.2.0-dev0"

container:
  mountPath: "/outDir"
  command:
    - python3
    - -m
    - polus.aithena.oaipmh_client
    - --from
    - "2024-10-16"
    - --format
    - "arXiv"
    - --outDir
    - /outDir

resources:
  requests:
    memory: "512Mi"
    cpu: "1"

persistentVolume:
  storage: 5Gi
  hostPath: /polus2/gerardinad/projects/aithena/.data/arxiv-download/

persistentVolumeClaim:
  storage: 5Gi