replicaCount: 1

image:
  repository: qdrant/qdrant
  pullPolicy: IfNotPresent
  tag: "v1.11.3"
  
service:
  type: NodePort
  port: 6333
  targetPort: 6333
  nodePort: 30333 

container:
  mountPath: "/qdrant/storage"
# resources:
  # requests:
  #   memory: "64Mi"
  #   cpu: "250m"
  # limits:
  #   memory: "128Mi"
  #   cpu: "500m"

persistentVolume:
  storage: 50Gi
  hostPath: /path/to/db-data

persistentVolumeClaim:
  storage: 50Gi

nodeSelector: {}

tolerations: []

affinity: {}
