# Default values for qdrantChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: agerardin/ai-review-app
  pullPolicy: IfNotPresent
  tag: "0.2.0-dev3"

service:
  type: NodePort
  port: 8765
  targetPort: 8766
  nodePort: 32066 

env:
  - name: OLLAMA_HOST
    value: "http://service-ollama-ollama-chart.ref.svc.cluster.local:11434"
  - name: QDRANT_HOST
    value: "service-qdrant-qdrant-chart.ref.svc.cluster.local"
  - name: QDRANT_PORT
    value: "6333"
  - name: APP_DATA_DIR
    value: "/.app-data"
  - name: DOC_COLLECTION
    value: nist_abstracts_NV-Embed-v1

container:
  mountPath: /.app-data

nodeSelector: {}

tolerations: []

affinity: {}

persistentVolume:
  storage: 5Mi
  hostPath: /polus2/gerardinad/projects/aithena/.test-data/.app-data

persistentVolumeClaim:
  storage: 5Mi
