apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ask-aithena-app-chart.fullname" . }}-runtime
  labels:
    {{- include "ask-aithena-app-chart.labels" . | nindent 4 }}
data:
  runtime.json: |
    {
      "appEnv": "{{ .Values.config.appEnv }}",
      "nodeEnv": "production",
      "internalApiUrl": "{{ .Values.config.internalApiUrl }}",
      "internalRabbitmqWsUrl": "{{ .Values.config.internalRabbitmqWsUrl }}"
    }
