{{- if .Values.vertex.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "litellm-chart.fullname" . }}-vertex-credentials
  labels:
    {{- include "litellm-chart.labels" . | nindent 4 }}
data:
  vertex_credentials.json: |
    {{- toJson .Values.vertex.credentials | nindent 4 }}
{{- end }}
