apiVersion: v1
kind: Secret
metadata:
  name: aithena-services-secret-0.1.0
type: Opaque
data:
  AZURE_OPENAI_API_VERSION: BASE64_ENCODED  # required, can leave as is
  AZURE_OPENAI_API_KEY: BASE64_ENCODED # required
  AZURE_OPENAI_ENDPOINT: BASE64_ENCODED # required