apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-aithena-services-0.1.0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi