apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-aithena-services-0.1.0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/polus2/velezramirezc2/microk8s-data/aithena-services"