  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

qdrant-chart:
  replicaCount: 1

  image:
    repository: qdrant/qdrant
    pullPolicy: IfNotPresent
    tag: "v1.11.3"
    
  service:
    type: NodePort
    port: 6333
    targetPort: 6333
    nodePort: 30333 

  container:
    mountPath: "/qdrant/storage"
  # resources:
    # requests:
    #   memory: "64Mi"
    #   cpu: "250m"
    # limits:
    #   memory: "128Mi"
    #   cpu: "500m"

  persistentVolume:
    storage: 50Gi
    hostPath: /path/to/db-data

  persistentVolumeClaim:
    storage: 50Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}


ollama-chart:
  replicaCount: 1

  image:
    repository: ollama/ollama
    pullPolicy: IfNotPresent
    tag: "0.3.10"

  service:
    type: NodePort
    port: 11434
    targetPort: 11434
    nodePort: 32434 

  container:
    mountPath: "/root/.ollama"

  persistentVolume:
    storage: 50Gi
    hostPath: /path/to/ollama-data

  persistentVolumeClaim:
    storage: 50Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}


aithena-services-chart:
  replicaCount: 1

  image:
    repository: agerardin/aithena-services
    pullPolicy: IfNotPresent
    tag: "0.1.0-dev3"

  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 32080 

  container:
    mountPath: "/mnt/config"
    # resources:
    #   requests:
    #     memory: "500Mi"
    #     cpu: "1"
    #   limits:
    #     memory: "2Gi"
    #     cpu: "1"

  secrets:
    - name: aithena-services-secret

  env:
    - name: OLLAMA_HOST
      value: "http://service-ollama.test-aithena.svc.cluster.local:11434"

  persistentVolume:
    storage: 5Mi
    hostPath: /path/to/aithena-services-data

  persistentVolumeClaim:
    storage: 5Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}


ai-review-app-chart:
 replicaCount: 1

image:
  repository: agerardin/ai-review-app
  pullPolicy: IfNotPresent
  tag: "0.2.0-dev3"

service:
  type: NodePort
  port: 8765
  targetPort: 8765
  nodePort: 32178

env:
  - name: QDRANT_HOST
    value: "qdrant-service.default.svc.cluster.local"
  - name: QDRANT_PORT
    value: "6333"
  - name: APP_DATA_DIR
    value: "/.app-data"
  - name: DEFAULT_COLLECTION
    value: "nist_abstracts_NV-Embed-v1"
  - name: DEFAULT_CHAT_MODEL
    value: "llama3.1"
  - name: AITHENA_SERVICE_URL
    value: "http://service-ais-aithena-services-chart.ref.svc.cluster.local:80"

container:
  mountPath: /.app-data

nodeSelector: {}

tolerations: []

affinity: {}

persistentVolume:
  storage: 5Mi
  hostPath: /path/to/ai-review-app-data

persistentVolumeClaim:
  storage: 5Mi

