{{- define "job-lib-chart.depl.tpl" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app: {{ include "chart.name" . }}
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
spec:
  template:
    spec:
      restartPolicy: {{ default .Values.container.restartPolicy "OnFailure" | quote }}

      # Mount volumes
      {{if .Values.persistentVolumeClaim}}
      volumes:
        - name: {{ include "storage.name" . | quote }}
          persistentVolumeClaim:
            claimName: {{ include "pvc.name" . | quote }}
      {{- end }}
      
      containers:
        - name: {{ include "chart.name" . }}
        
          # Image
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default .Values.image.pullPolicy "IfNotPresent" | quote }}

          # Mount all declared secrets
          {{- if .Values.secrets }}
          envFrom:
            {{- range .Values.secrets }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
          {{- end }}

          # Mount all declared configMaps
          {{- if .Values.configMaps }}
          envFrom:
            {{- range .Values.configMaps }}
            - configMapRef:
                name: {{ .name }}
            {{- end }}
          {{- end }}

          # Declare environment variables
          {{- if .Values.env }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}

          {{if .Values.container.command}}
          command: {{ toYaml .Values.container.command | nindent 12 }}
          {{- end }}

          # Mount paths
          {{- if .Values.container}}
          {{- if .Values.container.mountPath }}
          volumeMounts:
          - mountPath: {{ .Values.container.mountPath }}
            name: {{ include "storage.name" .}}
          {{- end }}        
          {{- end }}

          # Resources description
          {{- if .Values.resources }}
          resources:
            {{- if .Values.resources.requests }}
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            {{- end }}
            {{- if .Values.resources.limits }}
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
            {{- end }}
            {{- end }}
{{- end -}}

{{- define "job-lib-chart.depl" -}}
{{- include "job-lib-chart.util.merge" (append . "job-lib-chart.depl.tpl") -}}
{{- end -}}