apiVersion: v1
kind: Service
metadata:
  name: ollama-headless
  namespace: box
spec:
  clusterIP: None
  selector:
    app: ollama
  ports:
  - port: 11434
    targetPort: 11434
    protocol: TCP
    name: http
