# Default values for qdrantChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: agerardin/ask-aithena-agent
  pullPolicy: IfNotPresent
  tag: "0.1.2-dev2"

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30845 

env:
  - name: AITHENA_SERVICES_URL
    value: "http://service-ais.test-aithena.svc.cluster.local:80"
  - name: EMBED_MODEL
    value: "nomic-embed-text"
  - name: CHAT_MODEL
    value: "llama3.1:latest"
  - name: EMBEDDING_TABLE
    value: "openalex.nomic_embed_text_768"
  - name: SIMILARITY_N
    value: "10"
  # QDRANT ENV - deprecated
  # - name: DB_HOST
  #   value: "service-qdrant-qdrant-chart.ref.svc.cluster.local"
  # - name: DB_PORT
  #   value: "6333"
  # - name: DOC_COLLECTION
  #   value: "full_arxiv_abstracts_nomic768"

nodeSelector: {}

tolerations: []

affinity: {}

persistentVolume:
  storage: 5Mi
  hostPath: /path/to/ask-aithena-agent-data

persistentVolumeClaim:
  storage: 5Mi
