apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgai-vectorizer-worker
  namespace: box
spec:
  replicas: 6
  selector:
    matchLabels:
      app: pgai-vectorizer-worker
  template:
    metadata:
      labels:
        app: pgai-vectorizer-worker
    spec:
      containers:
      - name: pgai-vectorizer-worker
        image: timescale/pgai-vectorizer-worker:v0.11.4
        env:
        - name: PGAI_VECTORIZER_WORKER_DB_URL
          value: postgresql://AithenaAdmin:polus2has8@askaithena-db:5432/askaithena
        - name: PGAI_VECTORIZER_WORKER_CONCURRENCY
          value: "150"
        - name: PGAI_VECTORIZER_WORKER_POLL_INTERVAL
          value: "5s"
        - name: PGAI_VECTORIZER_WORKER_VECTORIZER_IDS
          value: "42"
        resources:
          requests:
            memory: "6Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "3"
